### ISSUE TITLE
初稿UI界面开发

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/linxin#1]
这个雷坤现在正在做，
正式类似微信的邻居版，具体细节，我会在这个issue里更新一些意见和反馈

**Comment by 12w21** [comment]
@ivanzhang2 @leikun222 
基本界面雷坤已经做好，现在经考虑，个人提出如下建议，请后续设计时参考落实，谢谢。
1.建议动态页面可以增加懂点医、懂点药、懂美味、点墨阁、群衣阁、爱你城、有剑气、有王法等等内容社交平台的文章和帖子的分享和评论，就像其它平台分享到微信朋友圈一样，互相导流，并为后来建立邻訫的圈子分享接口做好模型。
2.请设置小区成员列表的成员点击后进入成员详情页面，发现中的邻居圈每条动态的小区名点击进入小区详情，头像点击进入成员详情，朋友圈动态列表的头像和昵称都点击进入成员详情，后面的小区名点击进入小区详情。所有动态右下角都有（点赞、评论），并建议右上交能设置一个（X）用于表示不感兴趣此类动态。.建议小区详情页的右上角按钮为动态发布按钮，点击进入动态发布页，动态发布页建议设置文字、图片、小视频三项。
3.小区成员页面增加关注按钮（三个状态：未关注、已关注、互相关注），邻友页面也增加关注标签（已关注、互相关注和取消关注），邻居圈里显示与我有同在一小区的成员的动态（将来多了可以设置动态类别并选择关注），朋友圈里显示我关注了的成员的动态（如对方选择了屏蔽我，就不显示了），邻居圈、朋友圈和小区的动态都在头像下方设置显示相互关注状态，小区（未关注、已关注、互相关注、取消关注），邻居圈（未关注、已关注、互相关注），朋友圈（已关注、互相关注和取消关注）。
