### ISSUE TITLE
APP的介绍页

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/linxin#7]
就是介绍这个app是如何样的，类似： https://dongmeiwei.com/apps.

张友沛准备素材， 雷坤完成html页并上线到  http://linxinapp.com/ 首页..

王翀 测试

**Comment by leikun222** [comment]
友沛哥时这样安排的 他说介绍页先暂时不做，因为进到linxinapp.com这个网站来基本就能知道是干什么的了，不需要再介绍了，点交互的地方时直接弹出一个二维码的modal 用户扫一扫进行下载。

**Comment by ivanzhang2** [comment]
可以，那步需要app介绍页了，那这个issue我关闭了
